import Head from 'next/head'
import Image from 'next/image'
import { Navbar } from '../components/Navbar';


// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1 className="p-10 text-3xl font-bold text-red-500">GFG-KIIT</h1>
      
    </div>
  )
}
// import Head from 'next/head';
// import { Navbar } from '../components/Navbar';

// export default function Home() {
//   return (
//     <div>
//       <Head>
//         <title>Create Next App</title>
//         <link rel='icon' href='/favicon.ico' />
//       </Head>
//       <Navbar />
//       <div>Hello World</div>
//     </div>
//   );
// }